# TruffleHog Configuration for Azure/Databricks/GitHub CI/CD
# Optimized for enterprise Databricks projects on Azure

# Paths to exclude from scanning
exclude_paths:
  - .git/
  - .databricks/
  - .venv/
  - venv/
  - __pycache__/
  - "*.pyc"
  - node_modules/
  - .pytest_cache/
  - htmlcov/
  - dist/
  - build/
  - "*.egg-info/"
  - .coverage
  - "*.log"

# Detector Configuration - Optimized for Azure/Databricks
detectors:
  # Primary Platform (Required)
  - name: azure
    enabled: true
  - name: databricks
    enabled: true
  - name: github
    enabled: true
  
  # Generic Patterns (Safety Net)
  - name: generic-api-key
    enabled: true
  - name: uri
    enabled: true
  
  # Keys & Authentication (Common)
  - name: private-key
    enabled: true
  - name: jwt
    enabled: true
  
  # Databases (Databricks Integration)
  - name: sqlserver
    enabled: true
  - name: postgres
    enabled: true
  - name: mysql
    enabled: true
  - name: mongodb
    enabled: true

# Allowlist - Minimal and specific
allow:
  paths:
    - tests/fixtures/mock_data/README.md
    - docs/examples/placeholder_config.example
  
  regexes:
    # Documentation placeholders only
    - "example\\.com$"
    - "example\\.org$"
    - "localhost$"
    - "127\\.0\\.0\\.1$"
    
    # Databricks workspace URLs (public endpoints, not secrets)
    - "https://adb-[0-9]+\\.[0-9]+\\.azuredatabricks\\.net/?$"
    
    # Template variables
    - "\\$\\{[A-Z_]+\\}"     # ${API_KEY}
    - "\\{\\{[A-Z_]+\\}\\}"  # {{API_KEY}}
    - "<[A-Z_]+>"            # <API_KEY>

# Security Configuration
verify: true           # Verify secrets for severity classification
only-verified: false   # Catch ALL secrets (verified + unverified)
fail-verified: true    # Always fail on verified secrets

# Output Configuration
output-format: json    # JSON for CI/CD parsing
