name: CI/CD for Databricks Bundles
on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop
  workflow_dispatch:
    inputs:
      skip-linting:
        description: 'Skip linting checks'
        required: false
        type: boolean
        default: false
      skip-secret-scan:
        description: 'Skip secret scanning (emergency only)'
        required: false
        type: boolean
        default: false

permissions:
  id-token: write   # Required for OIDC authentication
  contents: read    # Required to checkout code
  security-events: write  # Required for security scanning results

jobs:
  # Secret Detection - Runs first to block pipeline if secrets found
  secret-scan:
    name: Secret Detection
    runs-on: ubuntu-latest
    if: ${{ !(github.event_name == 'workflow_dispatch' && github.event.inputs.skip-secret-scan == 'true') }}
    permissions:
      contents: read
      security-events: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # full history for comprehensive scan

      # Run TruffleHog via official Action
      - name: Run TruffleHog Secret Detection
        uses: trufflesecurity/trufflehog@main
        with:
          path: ./
          base: ${{ github.event.repository.default_branch }}
          head: HEAD
          extra_args: --only-verified --json --output trufflehog-results.json --no-update

      # Convert JSON → SARIF for GitHub Code Scanning
      - name: Convert JSON report to SARIF
        run: |
          echo "Installing TruffleHog CLI for SARIF conversion..."
          curl -sSfL https://raw.githubusercontent.com/trufflesecurity/trufflehog/main/scripts/install.sh | bash
          echo "Converting JSON to SARIF..."
          trufflehog convert --input trufflehog-results.json --format sarif --output trufflehog-results.sarif || true

      # Upload SARIF to GitHub Code Scanning Alerts
      - name: Upload SARIF to GitHub Security Alerts
        if: always()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: trufflehog-results.sarif
          category: trufflehog

      # Upload raw JSON results as artifact for audit
      - name: Upload TruffleHog JSON Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: trufflehog-report
          path: trufflehog-results.json

      # Human-readable console summary
      - name: Secret scan summary
        if: success()
        run: echo "No secrets detected - pipeline can proceed"

      - name: Secret scan failed
        if: failure()
        run: |
          echo "SECRETS DETECTED!"
          echo "Pipeline blocked to prevent credential exposure."
          echo "Please remove secrets and use GitHub Secrets or Azure Key Vault instead."
          exit 1

  # PR Validation - Always includes linting
  validate:
    needs: [secret-scan]
    if: |
      github.event_name == 'pull_request' && 
      (needs.secret-scan.result == 'success' || needs.secret-scan.result == 'skipped')
    uses: Himaan1502/ADB-Template/.github/workflows/reusable-ci-cd.yml@main
    with:
      environment: dev
      skip-linting: false  # Always run linting for PRs
    secrets:
      client-id: ${{ secrets.AZURE_CLIENT_ID }}
      tenant-id: ${{ secrets.AZURE_TENANT_ID }}
      subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

  # DEV Deployment - WITH Linting
  deploy-dev:
    needs: [secret-scan]
    if: |
      github.event_name != 'pull_request' && 
      (needs.secret-scan.result == 'success' || needs.secret-scan.result == 'skipped')
    uses: Himaan1502/ADB-Template/.github/workflows/reusable-ci-cd.yml@main
    with:
      environment: dev
      skip-linting: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.skip-linting == 'true' }}
    secrets:
      client-id: ${{ secrets.AZURE_CLIENT_ID }}
      tenant-id: ${{ secrets.AZURE_TENANT_ID }}
      subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

  # UAT Deployment - NO Linting (depends on dev success)
  deploy-uat:
    needs: [deploy-dev]
    if: |
      github.event_name != 'pull_request' && 
      needs.deploy-dev.result == 'success'
    uses: Himaan1502/ADB-Template/.github/workflows/reusable-ci-cd.yml@main
    with:
      environment: uat
      skip-linting: true  # Always skip linting for UAT - code already validated in dev
    secrets:
      client-id: ${{ secrets.AZURE_CLIENT_ID }}
      tenant-id: ${{ secrets.AZURE_TENANT_ID }}
      subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
