name: Deploy to UAT

on:
  push:
    branches:
      - uat
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy-uat:
    name: Deploy to UAT Environment
    uses: Himaan1502/ADB-Template/.github/workflows/reusable-ci-cd.yml@main
    with:
      environment: uat
      skip-linting: true  # Already validated in dev
    secrets:
      client-id: ${{ secrets.AZURE_CLIENT_ID }}
      tenant-id: ${{ secrets.AZURE_TENANT_ID }}
      subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
